### ISSUE TITLE
Power rankings need to be manually updated each week

### ISSUE THREAD

**Issue by dtcarls** [dtcarls/ff_bot#1]
Power rankings need to be manually updated each week until https://github.com/rbarton65/espnff/issues/31 is resolved and https://github.com/rbarton65/espnff/pull/32 is accepted

**Comment by dtcarls** [comment]
Good conversation going on here linked so I don't lose it. https://github.com/dtcarls/ff_bot/commit/a82b10b5f3e182355fe7f16eaeebbcfd6de65d92#comments

**Comment by dtcarls** [comment]
Continuing convo from https://github.com/dtcarls/ff_bot/commit/a82b10b5f3e182355fe7f16eaeebbcfd6de65d92#comments @raulvasquez @DBaryudin

See this commit in develop branch. https://github.com/dtcarls/ff_bot/commit/82e197d531848ce7a36d9a453036d608c150053d
Double check my logic before I publish to master. It seems current_week-1 and not current_week should be used for power ranks after running power ranks manually with weeks 1, 2, 3, 4, 5. 

I'd also like to try and bring in  @cawdev since they seem to be adding a lot and I basically used their algo with a couple slight tweeks for this fix.

**Comment by DBaryudin** [comment]
The code will iterate through the scores:
- Week 1: Count = 2
- Week 2: Count = 3
- Week 3: Count = 2 again, right?

**Comment by dtcarls** [comment]
Should be:
Week 1: Count = 1
Week 2: Count = 1
Week 3: Count = 2
Week 4: Count = 3
