### ISSUE TITLE
timing of annoucements

### ISSUE THREAD

**Issue by jplevel** [dtcarls/ff_bot#27]
consider using UTC to schedule the announcements, or disabling time zone settings all together. I live on the west coast so i changed the settings in Heroku to Los_Angeles.  The posting from the bot comes at specified times daily. Thus changing my made the messages come later then they should (for instance the thursday game matchup messages came mid game for me).

**Comment by dtcarls** [comment]
Planning to implement a variable timezone for Power rankings, Trophies, and the 7:30 am scoreboard recaps. This will leave Matchups, Close scores, and "post game" scoreboards aligned to actual game times.

**Comment by dtcarls** [comment]
Above comment implemented
